version: "3"
services:

  database:
    container_name: database
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Harry123!"
      ACCEPT_EULA: "Y"
      MSSQL_DB: "coursework"
      MSSQL_USER: "harry"
      MSSQL_PASSWORD: "Harry123!"